language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py27-django18-drf24
    - TOX_ENV=py27-django18-drf36
    - TOX_ENV=py27-django110-drf36
    - TOX_ENV=py27-django111-drf36

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
